/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package bitmap.transformer;


package bitmap.transformer;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
     @Test void grayScale() {
        Bitmap test = new Bitmap("./app/src/main/resources/Input/inputImage.bmp","./app/src/main/resources/Onput", "first.bmp");
        assertEquals(true, test.readFile());

        Bitmap bitmap = new Bitmap();
        bitmap.setOutputFilePath("./app/src/main/resources/Onput");
        bitmap.setInputFilePath("./app/src/main/resources/Input/inputImage.bmp");
        bitmap.setNewFileName("first.bmp");

        assertEquals(bitmap, test);

    }
}
