/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package bitmap.transformer;


package bitmap.transformer;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void grayScale() {
        App test = new App();


    }
}
